// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbNqocrKq-SlpcxzzNS0vnMbkg6BKaMmo',
    appId: '1:1078917942228:web:1943d3b9886b80e6d9a441',
    messagingSenderId: '1078917942228',
    projectId: 'myportfolio-60082',
    authDomain: 'myportfolio-60082.firebaseapp.com',
    storageBucket: 'myportfolio-60082.firebasestorage.app',
    measurementId: 'G-8BFEZP1SCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHpnQCq_jravCsldawsB9M-A4p8OfjZmg',
    appId: '1:1078917942228:android:0abc543c7f2f958bd9a441',
    messagingSenderId: '1078917942228',
    projectId: 'myportfolio-60082',
    storageBucket: 'myportfolio-60082.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8464NwPNG_AdPE6JIZSGv8bN_EdTD2bQ',
    appId: '1:1078917942228:ios:28bfc2fd94483904d9a441',
    messagingSenderId: '1078917942228',
    projectId: 'myportfolio-60082',
    storageBucket: 'myportfolio-60082.firebasestorage.app',
    iosBundleId: 'app.myportfolio.com',
  );
}
